#!/usr/bin/env bash
# configure nginx on the server.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

#Change index.html to read "Holberton School"
sudo echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
sudo /etc/init.d/nginx start
