#!/usr/bin/env bash
# configure nginx on the server.
sudo apt-get -y update && sudo apt-get install -y nginx

#Change index.html to read "Holberton School"
echo "holberton School" | sudo tee /var/www/html/index.html
