#!/usr/bin/env bash
# bash script to replace line with multiple lines with sed
sudo apt-get -y update
sudo apt-get -y install nginx

#Change index.html to read "Holberton School"
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html

lines="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "26i $lines" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
sudo service nginx start
