#!/usr/bin/env bash
# Script to Debbug and NGINX server

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-ena
bled/default
sudo /etc/init.d/nginxs stop
sudo /etc/init.d/nginx start
