#!/usr/bin/env bash
#Print the time from 00:01 to 12:59
hour=0
while [ $hour -le 12 ];
do
    echo "Hour:" $hour
    minute=1
    while [ $minute -le 59 ];
    do
	echo $minute
	let minute=minute+1
    done
    let hour=$hour+1
done
